#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and "I am invincible!!!" when recieving a signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
	do echo "To infinity and beyond"
	sleep 2
done
